(package "npm-pkgs"
         "1.1.1"
         "An npm packages client")

(website-url "https://github.com/jcs-elpa/npm-pkgs")
(keywords "convenience" "npm" "packages" "client")

(package-file "npm-pkgs.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "request")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
